export const gatosEnAdopcion = [
  {
    name: 'Luna',
    age: '2 años',
    gender: 'Hembra',
    description: 'Cariñosa y juguetona, ideal para familias.',
    image: '/images/gatos/luna.webp',
    tags: ['Juguetona', 'Cariñosa', 'Familiar'],
  },
  {
    name: 'Simba',
    age: '1 año',
    gender: 'Macho',
    description: 'Curioso y sociable, le encanta explorar.',
    image: '/images/gatos/simba.webp',
    tags: ['Curioso', 'Sociable', 'Explorador'],
  },
  {
    name: 'Milo',
    age: '3 años',
    gender: 'Macho',
    description: 'Tranquilo y dulce, busca un hogar estable.',
    image: '/images/gatos/milo.webp',
    tags: ['Tranquilo', 'Dulce', 'Estable'],
  },
  {
    name: 'Nina',
    age: '6 meses',
    gender: 'Hembra',
    description: 'Muy activa y divertida, perfecta para jugar.',
    image: '/images/gatos/nina.webp',
    tags: ['Activa', 'Divertida', 'Juguetona'],
  },
  {
    name: 'Toby',
    age: '4 años',
    gender: 'Macho',
    description: 'Le encanta dormir y recibir mimos.',
    image: '/images/gatos/toby.webp',
    tags: ['Dormilón', 'Mimoso', 'Tranquilo'],
  },
  {
    name: 'Cleo',
    age: '2 años',
    gender: 'Hembra',
    description: 'Independiente pero cariñosa con su familia.',
    image: '/images/gatos/cleo.webp',
    tags: ['Independiente', 'Cariñosa', 'Familiar'],
  },
  {
    name: 'Leo',
    age: '1 año',
    gender: 'Macho',
    description: 'Muy sociable con otros gatos y niños.',
    image: '/images/gatos/leo.webp',
    tags: ['Sociable', 'Amigable', 'Niños'],
  },
  {
    name: 'Maya',
    age: '5 años',
    gender: 'Hembra',
    description: 'Senior tranquila, busca hogar definitivo.',
    image: '/images/gatos/maya.webp',
    tags: ['Senior', 'Tranquila', 'Definitivo'],
  },
  {
    name: 'Sasha',
    age: '8 meses',
    gender: 'Hembra',
    description: 'Juguetona y curiosa, ideal para compañía.',
    image: '/images/gatos/sasha.webp',
    tags: ['Juguetona', 'Curiosa', 'Compañía'],
  },
  {
    name: 'Max',
    age: '2 años',
    gender: 'Macho',
    description: 'Le encanta trepar y observar desde lo alto.',
    image: '/images/gatos/max.webp',
    tags: ['Trepar', 'Observador', 'Activo'],
  },
  {
    name: 'Olivia',
    age: '3 años',
    gender: 'Hembra',
    description: 'Muy dulce y tranquila, perfecta para piso.',
    image: '/images/gatos/olivia.webp',
    tags: ['Dulce', 'Tranquila', 'Piso'],
  },
  {
    name: 'Rayo',
    age: '1 año',
    gender: 'Macho',
    description: 'Activo y curioso, necesita espacio para jugar.',
    image: '/images/gatos/rayo.webp',
    tags: ['Activo', 'Curioso', 'Jugar'],
  },
  {
    name: 'Mimi',
    age: '2 años',
    gender: 'Hembra',
    description: 'Le encanta la compañía humana.',
    image: '/images/gatos/mimi.webp',
    tags: ['Compañía', 'Cariñosa', 'Amigable'],
  },
  {
    name: 'Tom',
    age: '4 años',
    gender: 'Macho',
    description: 'Muy tranquilo, ideal para personas mayores.',
    image: '/images/gatos/tom.webp',
    tags: ['Tranquilo', 'Mayores', 'Calmado'],
  },
  {
    name: 'Lola',
    age: '7 meses',
    gender: 'Hembra',
    description: 'Pequeña y juguetona, busca familia activa.',
    image: '/images/gatos/lola.webp',
    tags: ['Pequeña', 'Juguetona', 'Activa'],
  },
  {
    name: 'Nico',
    age: '2 años',
    gender: 'Macho',
    description: 'Sociable y cariñoso, se adapta fácil.',
    image: '/images/gatos/nico.webp',
    tags: ['Sociable', 'Cariñoso', 'Adaptable'],
  },
  {
    name: 'Kira',
    age: '3 años',
    gender: 'Hembra',
    description: 'Le encanta el sol y los rincones tranquilos.',
    image: '/images/gatos/kira.webp',
    tags: ['Sol', 'Tranquila', 'Rincones'],
  },
  {
    name: 'Gala',
    age: '1 año',
    gender: 'Hembra',
    description: 'Muy activa y divertida, perfecta para jugar.',
    image: '/images/gatos/gala.webp',
    tags: ['Activa', 'Divertida', 'Jugar'],
  },
  {
    name: 'Chispa',
    age: '2 años',
    gender: 'Macho',
    description: 'Curioso y explorador, busca aventuras.',
    image: '/images/gatos/chispa.webp',
    tags: ['Curioso', 'Explorador', 'Aventurero'],
  },
  {
    name: 'Bimba',
    age: '5 años',
    gender: 'Hembra',
    description: 'Senior cariñosa, busca hogar tranquilo.',
    image: '/images/gatos/bimba.webp',
    tags: ['Senior', 'Cariñosa', 'Tranquila'],
  },
];
